# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Your github token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
